name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.14.0"
      - name: Build OMDb-API-Filter-Example
        run: |
          npm ci
          npm run build
        env: 
         REACT_APP_API_KEY: ${{ secrets.REACT_APP_API}}
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
